export const ROLES = {
  MASTER_SELLER: "MASTER_SELLER",
  NORMAL_SELLER: "NORMAL_SELLER",
  CUSTOMER: "CUSTOMER",
};

export const SELLER_ROLES = [ROLES.MASTER_SELLER, ROLES.NORMAL_SELLER];
export const ALL_ROLES = Object.values(ROLES);
